### ISSUE TITLE
Can't compile in macOS Sierra 10.12.1

### ISSUE THREAD

**Issue by toyoxx** [ros/common_tutorials#15] opened 2016-11-17 15:00 UTC
Hello.

I'm trying to install ROS Jade on macOS 10.12.1, using clang++ and libc++, but I keep getting the following error when trying to compile common_tutorials, specifically nodelet_math_tutorial. The compiler basically tells me that There is no definition of several variables in the global namespace. You can see the output [here](https://gist.github.com/toyoxx/8a8123ecf5a0ee7828a3f5745e125697). I have tried several approaches, such as changing from libc++ to libstdc++, but then its deprecated and some other packages fail. I have no idea what to do! 

Thanks

**Comment by dirk-thomas** [comment] 2016-11-17 15:17
The stack traces look like that the actual package the problem is coming from is `class _loader`. Maybe you should fill the ticket there instead. You could also ask on answers.ros.org if others might have an answer for you.

**Comment by toyoxx** [comment] 2016-11-17 16:56
Thanks! I will ask there then.

**Comment by dirk-thomas** [comment] 2016-11-17 17:06
Closing in favor of ros/class_loader#44.

**Closed as completed by dirk-thomas** 2016-11-17 17:06 UTC
Labels: duplicate
